name: Vouch Server Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "server/**"
  push:
    branches:
      - main
    paths:
      - "server/**"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Run tests
        run: npm test
        working-directory: ./server
